In [1]:
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:95% !important; }</style>"))

- - - 
# Contenido
**Bibliotecas (library): numpy**
- - -

### numpy: python numerico

In [1]:
import numpy as np

In [2]:
np.pi

3.141592653589793

In [4]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [5]:
pi

NameError: name 'pi' is not defined

In [6]:
from numpy import pi

In [9]:
np.cos(pi)

-1.0

In [7]:
pi

3.141592653589793

** Ejercicio.** Escribe una función que calcule el volumen de una esfera 
al dar como argumento el radio.

In [1]:
from numpy import *

In [11]:
cos(pi)

-1.0

**Un poco de color con markdown language**

`<font color=blue>Azul</font>`

### <font color=blue>Vectores y operaciones con vectores</font>

In [18]:
a = array( [1,2,-1,100] )

In [19]:
a

array([  1,   2,  -1, 100])

In [20]:
a.dtype

dtype('int64')

In [27]:
b = 4J*ones(10)
print (b)

[0.+4.j 0.+4.j 0.+4.j 0.+4.j 0.+4.j 0.+4.j 0.+4.j 0.+4.j 0.+4.j 0.+4.j]


In [28]:
b.dtype

dtype('complex128')

In [29]:
a = np.arange(0.,10.,0.1)

In [30]:
print (a)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7
 1.8 1.9 2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9 3.  3.1 3.2 3.3 3.4 3.5
 3.6 3.7 3.8 3.9 4.  4.1 4.2 4.3 4.4 4.5 4.6 4.7 4.8 4.9 5.  5.1 5.2 5.3
 5.4 5.5 5.6 5.7 5.8 5.9 6.  6.1 6.2 6.3 6.4 6.5 6.6 6.7 6.8 6.9 7.  7.1
 7.2 7.3 7.4 7.5 7.6 7.7 7.8 7.9 8.  8.1 8.2 8.3 8.4 8.5 8.6 8.7 8.8 8.9
 9.  9.1 9.2 9.3 9.4 9.5 9.6 9.7 9.8 9.9]


In [31]:
l = np.linspace(0,10,101)

In [32]:
print (l)

[ 0.   0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  0.9  1.   1.1  1.2  1.3
  1.4  1.5  1.6  1.7  1.8  1.9  2.   2.1  2.2  2.3  2.4  2.5  2.6  2.7
  2.8  2.9  3.   3.1  3.2  3.3  3.4  3.5  3.6  3.7  3.8  3.9  4.   4.1
  4.2  4.3  4.4  4.5  4.6  4.7  4.8  4.9  5.   5.1  5.2  5.3  5.4  5.5
  5.6  5.7  5.8  5.9  6.   6.1  6.2  6.3  6.4  6.5  6.6  6.7  6.8  6.9
  7.   7.1  7.2  7.3  7.4  7.5  7.6  7.7  7.8  7.9  8.   8.1  8.2  8.3
  8.4  8.5  8.6  8.7  8.8  8.9  9.   9.1  9.2  9.3  9.4  9.5  9.6  9.7
  9.8  9.9 10. ]


In [6]:
a = array( [1., 4., 7. ])
b = array( [1., 2., -2. ])

In [34]:
print (a+b)
print (a-b)
print (a*b)
print (a/b) 
print (a**b)

[2. 6. 5.]
[0. 2. 9.]
[  1.   8. -14.]
[ 1.   2.  -3.5]
[ 1.         16.          0.02040816]


In [35]:
1/49

0.02040816326530612

**Ejercicio.** Crea un vector v con 100 entradas iguales a -3.

In [41]:
v = -3*ones(100)


**Ejercicio.** Sumar los primeros 100 números enteros.

**Ejercicio.** Guardar en un arreglo 100 números aleatorios entre 0 y 1.

In [3]:
%%time
a = random.random(1000000000)

CPU times: user 6.69 s, sys: 1.51 s, total: 8.2 s
Wall time: 8.2 s


**Ejercicio.** Obtener el valor medio de 100 números aleatorios.

In [4]:
%%time
a.mean()

CPU times: user 657 ms, sys: 1.05 ms, total: 658 ms
Wall time: 655 ms


0.49999207491430225

In [39]:
a.mean?

**Productos entre vectores**

In [8]:
dot(a,b)

-5.0

In [9]:
cross(a,b)

array([-22.,   9.,  -2.])

In [10]:
vdot(a,b)

-5.0

In [13]:
a = array( [1J, 4., 7. ])
b = array( [1J, 2., -2. ])

In [15]:
dot(a,b)

(-7+0j)

In [16]:
vdot(a,b)

(-5+0j)

**función `np.conj( )`

In [18]:
dot( conj(a),b )

(-5+0j)

In [44]:
np.vdot(a,b)

(-5+0j)

**Funciones evaluadas en cada elemento de un vector**

In [20]:
def gauss(x):
    return 1./ (sqrt(2.)) * exp(-x*x / 2.)

In [21]:
gauss( linspace(-5,5) )

array([2.63514173e-06, 7.16007513e-06, 1.86613524e-05, 4.66531081e-05,
       1.11874210e-04, 2.57330532e-04, 5.67759729e-04, 1.20157196e-03,
       2.43919724e-03, 4.74958854e-03, 8.87109006e-03, 1.58931478e-02,
       2.73120809e-02, 4.50206323e-02, 7.11836617e-02, 1.07959532e-01,
       1.57055660e-01, 2.19158402e-01, 2.93342232e-01, 3.76619665e-01,
       4.63813437e-01, 5.47892800e-01, 6.20811558e-01, 6.74739177e-01,
       7.03435033e-01, 7.03435033e-01, 6.74739177e-01, 6.20811558e-01,
       5.47892800e-01, 4.63813437e-01, 3.76619665e-01, 2.93342232e-01,
       2.19158402e-01, 1.57055660e-01, 1.07959532e-01, 7.11836617e-02,
       4.50206323e-02, 2.73120809e-02, 1.58931478e-02, 8.87109006e-03,
       4.74958854e-03, 2.43919724e-03, 1.20157196e-03, 5.67759729e-04,
       2.57330532e-04, 1.11874210e-04, 4.66531081e-05, 1.86613524e-05,
       7.16007513e-06, 2.63514173e-06])

---
## ¡Alerta importante!
**Sobreescritura de valores**

In [28]:
a = array([0, 1, 2, 3])

In [29]:
print (a[0], a[2])

0 2


In [30]:
b = array(a[1:3])
print (b)

[1 2]


In [31]:
b[1] = 10 # b no es una copia es una 'vista'

In [32]:
b

array([ 1, 10])

In [33]:
a  # ¡también cambia!

array([0, 1, 2, 3])

In [34]:
# lo mismo pasa en las listas
l=[1,2,3]; k=l; k[1] = 10

In [35]:
l

[1, 10, 3]

--- 
## Matrices

In [36]:
M = array( [ [1, 2], [3, 4] ] )
print (M)

[[1 2]
 [3 4]]


In [37]:
B = array( [ [1, 2], [0, 1] ] )

In [38]:
B

array([[1, 2],
       [0, 1]])

In [39]:
M*B

array([[1, 4],
       [0, 4]])

In [40]:
dot(M,B)

array([[ 1,  4],
       [ 3, 10]])

**Cambiar forma de una matriz**

In [42]:
M.shape

(2, 2)

In [43]:
M.shape = (4, 1); print (M)

[[1]
 [2]
 [3]
 [4]]


In [44]:
M.reshape( 2, 2 )

array([[1, 2],
       [3, 4]])

**Operaciones comunes de una matriz**

In [46]:
identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [47]:
arange(3)

array([0, 1, 2])

In [48]:
diag( arange(3) )

array([[0, 0, 0],
       [0, 1, 0],
       [0, 0, 2]])

---
## Álgebra lineal

In [49]:
M = array( [[0.5, 0.5], [0.2, 0.8]] )
v = array([3, 5])

In [50]:
M

array([[0.5, 0.5],
       [0.2, 0.8]])

In [51]:
v

array([3, 5])

In [52]:
dot(M, v)

array([4. , 4.6])

In [53]:
M*v

array([[1.5, 2.5],
       [0.6, 4. ]])

In [54]:
dot(M,M)

array([[0.35, 0.65],
       [0.26, 0.74]])

**Ejercicio:** Utiliza el método de potencias para calcular el eigenvector de una matriz cuadrada $M$ correspondiente al eigenvalor de mayor módulo. Este método consiste en considerar la iteración $M^n \cdot v$.

In [56]:
v = array([-1,0]) 

In [58]:
for n in arange(100):
    v  = dot(M, v)/linalg.norm(dot(M, v))
print (v)

[-0.70710678 -0.70710678]


In [60]:
linalg.eig(M)[1]

array([[-0.92847669, -0.70710678],
       [ 0.37139068, -0.70710678]])

In [61]:
linalg.eig(M)[0]

array([0.3, 1. ])

**Algunos ejercicios de python:** Los primeros tres son directos y los segundos tres son más elabrorados.

1. Encontrar en qué valor $x$ se encuentra el máximo de la función $f(x)$. Considere la función $f(x)=-(x-3)^4$

2. En un arreglo de 100 número aleatorios entre 0 y 1, contar cuántos elementos son mayores a 0.5.

3. Graficar la función coseno en el intervalo de $-5\pi$ a $5\pi$ sólo cuando la función sea negativa.

4. Generar un conjunto de 100 matrices simétricas con entradas aleatorias de 2x2 y calcular el promedio de su determinante y el promedio de su traza.

5. Encontrar el mínimo de la función $(x-3)^4$ utilizando el método de Newton. De el valor inicial de 1.

6. Resolver el oscilador armónico utilizando el método de Euler. Elije las condiciones iniciales a tu gusto. Grafique la solución, es decir $x(t)$.